import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const read=p=>fs.readFileSync(new URL('../miniprogram/'+p,import.meta.url),'utf8');
const profile={id:'EN-Test',key:'id:EN-Test',type:'people',name:'同名',markets:[],categories:[],summary:'简介'};
function catalogHarness(){let queue=[];const ctx={module:{exports:{}},wx:{request(o){const value=queue.shift();value instanceof Error?o.fail(value):o.success({statusCode:200,data:value});}}};vm.runInNewContext(read('utils/research-profiles.js'),ctx);return {...ctx.module.exports,send(...r){queue.push(...r);}};}
const manifest=(hash='a'.repeat(64),n=1)=>({schemaVersion:'MINI-ENTITY-PROFILES-V1',contentHash:hash,profileCount:n});
test('catalog validates paired counts, retains last good snapshot and strips unlisted fields',async()=>{const h=catalogHarness();h.send(manifest(),{...manifest(),profiles:[{...profile,career:['private']}]});await h.refreshResearchProfiles();assert.equal(h.getResearchProfiles().length,1);assert.equal(h.getResearchProfiles()[0].career,undefined);
for(const bad of [{...manifest('b'.repeat(64)),profileCount:2,profiles:[profile]},{...manifest('b'.repeat(64)),profiles:[{...profile,markets:['unknown']}]},new Error('offline')]){h.send(manifest('b'.repeat(64)),bad);await assert.rejects(h.refreshResearchProfiles());assert.equal(h.getResearchProfiles()[0].id,profile.id);}});
test('stable uppercase IDs and aliases survive lookups; same-name people stay separate',()=>{const lib=require('../miniprogram/utils/entity-library.js');const cards=[{id:'a',company:'Acme',category:'AI',date:'2026-01-01'}];const library=lib.buildEntityLibrary(cards,{a:{founders:[{name:'同名',entityId:'EN-A'},{name:'同名',entity_id:'EN-B'}]}});assert.equal(library.people.length,2);assert.equal(library.companies[0].founders.length,2);assert.equal(lib.findEntity(library,'people','id:EN-A').name,'同名');});
function pageHarness(){let page,identity='a',resolve,reject;let profiles=[];const state={index:{cards:[]},details:{}};const payment={getSessionIdentity:()=>identity,hasAuthToken:()=>false,fetchProtectedContent:()=>new Promise((a,b)=>{resolve=a;reject=b;})};vm.runInNewContext(read('pages/entity-detail/index.js'),{Page:p=>page=p,wx:{showShareMenu(){}},require:p=>p.includes('payment')?payment:p.includes('research-profiles')?{getResearchProfiles:()=>profiles,refreshResearchProfiles:async()=>profiles}:p.includes('live-data')?{getFundingData:()=>state}:p.includes('entity-library')?require('../miniprogram/utils/entity-library.js'):p.includes('metered-access')?{resolveDetailAccess:()=>({contentLocked:false}),protectedResourceId:v=>v,contentLockReason:()=> 'expired'}:{}});page.data=JSON.parse(JSON.stringify(page.data));page.setData=v=>Object.assign(page.data,v);return {page,identity:v=>identity=v,resolve:v=>resolve(v),reject:v=>reject(v),profiles:v=>profiles=v};}
test('shared ID-only entry has a visible preview and rejects cross-account late protected replies',async()=>{const h=pageHarness();h.page.onLoad({type:'people',key:'id:EN-A',from:'share'});assert.ok(h.page.data.entity);h.identity('b');h.resolve({name:'Old account',publicProfile:{sections:['secret']}});await new Promise(r=>setImmediate(r));assert.equal(h.page.data.entity.publicProfile,undefined);});
test('expired or second guest detail clears full content and leaves gate and name visible',async()=>{for(const status of ['expired','unregistered']){const h=pageHarness();h.page.type='people';h.page.key='id:EN-A';h.page.name='人物';h.page.data.entity={name:'人物',publicProfile:{sections:['secret']}};const pending=h.page.verifyServerAccess();h.reject({statusCode:403,accessState:status});await pending;assert.equal(h.page.data.contentLocked,true);assert.equal(h.page.data.entity.publicProfile,undefined);assert.equal(h.page.data.entity.name,'人物');}});
test('research directory deduplicates unique institution aliases without merging same-name people or unknown markets',()=>{const ctx={module:{exports:{}},require:p=>p.includes('research-profiles')?{getResearchProfiles:()=>[{...profile,type:'investors',legacyInvestorKey:'同名'},{...profile,id:'EN-B',key:'id:EN-B'}]}:{buildEntityLibrary:()=>({investors:[{type:'investors',key:'同名',name:'同名',markets:['china'],categories:[]}],people:[]})}};vm.runInNewContext(read('utils/directory.js'),ctx);assert.equal(ctx.module.exports.directory({index:{cards:[]}}, {market:'all'}).total,2);assert.equal(ctx.module.exports.directory({index:{cards:[]}}, {market:'global'}).total,0);});
